### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by andriyrizhiy** [google/sky-optimization#1]
Are you planning to publish your accurate sky-mask dataset?

**Comment by orlyliba** [comment]
We have published the accurate sky mask dataset based on the ADE20K dataset on the GitHub page. Unfortunately, we are unable to publish our internal dataset.

**Comment by andriyrizhiy** [comment]
How to download ADE20K accurate sky masks. when I follow the link from this https://github.com/google/sky-optimization/tree/master/sky-mask-datasets I get form with auntification:
![image](https://user-images.githubusercontent.com/41432542/85264021-bd1b9c80-b478-11ea-88c5-c9c05df00458.png)

**Comment by orlyliba** [comment]
We have updated the link.
Sorry for your inconvenience.
Please let me know if there are any other issues or questions.

**Comment by andriyrizhiy** [comment]
How to download dataset from this google cloud?

**Comment by orlyliba** [comment]
Please try:
https://cloud.google.com/storage/docs/gsutil/commands/cp

**Comment by andriyrizhiy** [comment]
Can you add share link to all folders? not only for images_$folder$ and original_$folder$
![image](https://user-images.githubusercontent.com/41432542/85852628-a4cdb980-b7b9-11ea-871f-11df60d76aea.png)

**Comment by BruceWang1996** [comment]
> Can you add share link to all folders? not only for images_$folder$ and original_$folder$
> ![image](https://user-images.githubusercontent.com/41432542/85852628-a4cdb980-b7b9-11ea-871f-11df60d76aea.png)

Have you downloaded the dataset? I meet an error when I attempt to  download it by gsutil.
![image](https://user-images.githubusercontent.com/43333807/86427660-566e6c80-bd1d-11ea-8fe9-447355a0b04f.png)
