### ISSUE TITLE
Parameter optimization 

### ISSUE THREAD

**Issue by yggs1401** [google/sky-optimization#12]
Hello!

Can you please describe a little bit the chroma and luma tuning and the best values for them? Thank you!

**Comment by orlyliba** [comment]
Are you referring to tuning the smoothness in the guided filter?
The values depend on your task and on how noisy the reference image is.
You can separate the desired smoothness based on chroma and luma and the values can be different if the noise in the guide is different.
As noted in the supplementary (https://arxiv.org/pdf/2006.10172.pdf) we used 0.01, but for yourtask the values may be different.

**Comment by yggs1401** [comment]
Yes, I am referring to tuning the smoothness.

**Comment by orlyliba** [comment]
Closing this for now. LMK if you have further questions.
