### ISSUE TITLE
Density estimation：the pi of "undetermined" pix is about 63493

### ISSUE THREAD

**Issue by xiongzhu666** [google/sky-optimization#16]
Hi ,about Density estimation, I had implement gf_guided_filter and I want to add “de”，but I face the problem as below
I get the pi value of "undetermined" pix is about 63493 based on Equation 8 and Equation 9，what else did I ignore？？

**Comment by misaka-10032** [comment]
pi is density, not probability, so being greater than 1 is normal. I am not sure about which pixel you predict, but having a large value indicates the pixel is very likely to be sky.

**Comment by misaka-10032** [comment]
Also we computed the density in the log scale to save some precision loss. `log(63493)~=4.8`, which seems reasonable to me.
