### ISSUE TITLE
About download the datasets form google cloud.

### ISSUE THREAD

**Issue by BruceWang1996** [google/sky-optimization#2]
![image](https://user-images.githubusercontent.com/43333807/86426793-21f9b100-bd1b-11ea-89de-a5be866257cf.png)
help, thank you!

**Comment by BruceWang1996** [comment]
And when I download some files from other google cloud count, there isn't any error appear.
![image](https://user-images.githubusercontent.com/43333807/86427138-f88d5500-bd1b-11ea-974b-a4bed655d7cc.png)

**Comment by BruceWang1996** [comment]
Can you upload the dataset to GoogleDrive? Thank you very much!

**Comment by andriyrizhiy** [comment]
for me 
`gsutil -m cp -r  gs://cvprw2020_sky_seg/public_data/ .`
works

**Comment by andriyrizhiy** [comment]
before run `gsutil -m cp` you should run 'gcloud init'. I run with '--console-only --skip-diagnostics'

**Comment by orlyliba** [comment]
@BruceWang1996  Were you able to download the data?

**Comment by orlyliba** [comment]
We've enable the repository for anonymous access. Can you please retry?

**Comment by misaka-10032** [comment]
Closing for now. Please feel free to reopen.
