### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by andriyrizhiy** [google/sky-optimization#3]
Can you provide source code and your models?

**Comment by orlyliba** [comment]
Unfortunately we are not able to provide our code and models at this time.
Hopefully the provided datasets will enable you to train a sky segmentation model.
I did a quick search on github and found these projects which you can use to train a segmentation model:
https://github.com/notha99y/UNet
https://github.com/zhixuhao/unet
https://github.com/wuyang0329/unet
