### ISSUE TITLE
Training process

### ISSUE THREAD

**Issue by andriyrizhiy** [google/sky-optimization#4]
Question about training your network. When you training UNet, what do you do with labels? Do you use "probabilities" after guided filter algorithm or do you use binary labels (with some threshold after  guided filter)? If you wrote about training process somewhere in the paper, please show where. Thank you

**Comment by orlyliba** [comment]
The labels are the probabilities and we do not binarize them. This is a strength of using continuous-valued masks. We didn't provide a lot of details about the training process in the paper because there was nothing unique or nonstandard in the training process. Do you have any specific questions?
