### ISSUE TITLE
Question about Density estimation algorithm

### ISSUE THREAD

**Issue by andriyrizhiy** [google/sky-optimization#5]
in Section B you provide Equation 8:
![image](https://user-images.githubusercontent.com/41432542/86830330-3a145c00-c09e-11ea-8e66-5a086fca50ce.png)
and when I try to implement this I am faced with a problem. I tried to calculate the minimum and maximum probability, and got it [0,63493.6]
Steps:
1. If I have image with [0..1] pixels range, 
![image](https://user-images.githubusercontent.com/41432542/86830980-01c14d80-c09f-11ea-86ea-e52866137841.png)
this sum in range [0..3]
2. If I divide this sum with sigma=0.01 (from paper):
![image](https://user-images.githubusercontent.com/41432542/86831140-346b4600-c09f-11ea-8d06-1325c650596c.png)
I have range [0..15000]
3. with minus
![image](https://user-images.githubusercontent.com/41432542/86831331-6f6d7980-c09f-11ea-8bff-c382e6b1ff54.png)
I have [-15000..0]
4. with exp
![image](https://user-images.githubusercontent.com/41432542/86831396-82804980-c09f-11ea-9988-512dc182c346.png)
range = [0..1]
5. this part is constant:
![image](https://user-images.githubusercontent.com/41432542/86831498-a17edb80-c09f-11ea-95da-269798f7fb31.png)
and equal to 63493.6 (https://www.wolframalpha.com/input/?i=1%2F%282*pi*%280.01%29%5E2%29%5E%283%2F2%29)
and when we multiply range [0..1] to 63493.6 we get range [0..63493.6]

So, my question is: The probability should be within such limits? Is it possible to get this probability within [0..1]? Because you use threshold pc = 0.6 in Section 3.2 after Density estimation algorithm

**Comment by misaka-10032** [comment]
To clarify, what we get here is a probability density, not probability itself, so it's not limited within [0, 1], as long as the integral is 1.
https://en.wikipedia.org/wiki/Probability_density_function

The range seems about right. The computation is done in the log scale, so the log range is [-inf..11].

Please be aware that the precision could be an issue if it's not handled properly for LogSumExp
https://en.wikipedia.org/wiki/LogSumExp

**Comment by andriyrizhiy** [comment]
So, p_i = log(p_i)? And for  threshold pc = 0.6 in Section 3.2 you use log(p)?

**Comment by misaka-10032** [comment]
No. This is p_c itself. The intuition is pick a value somewhere below 1, because the density of a uniform distribution is 1. Choosing some value below one is just to encourage triggering, because we do want to see the sky in-between trees.

**Comment by andriyrizhiy** [comment]
Understand. Thank you!
